export const arr = [
  {
    subjectName: "Engineering Mathematics-I ",
    subjectCode: "BMS-01/BAS-01",
    totalMarks: 100,
    credits: 4,
    type: "Theory",
  },
  {
    subjectName: "Engineering Physics-I",
    subjectCode: "BPM-01/BAS-02",
    totalMarks: 100,
    credits: 5,
    type: "Theory",
  },
  {
    subjectName: "Introduction to C & Functional Programming",
    subjectCode: "BCS-02",
    totalMarks: 100,
    credits: 5,
    type: "Theory",
  },
  {
    subjectName: "Principles of Electrical Engineeering",
    subjectCode: "BEE-01",
    totalMarks: 100,
    credits: 5,
    type: "Theory",
  },
  {
    subjectName: "Professional Communication",
    subjectCode: "BHM-01/BAS-03",
    totalMarks: 100,
    credits: 4,
    type: "Theory",
  },
  {
    subjectName: "Software Lab-I",
    subjectCode: "BCS-03",
    totalMarks: 100,
    credits: 2,
    type: "Practical",
  },
  {
    subjectName: "Engineering Mathematics-II ",
    subjectCode: "BMS-02/BAS-07",
    totalMarks: 100,
    credits: 4,
    type: "Theory",
  },
  {
    subjectName: "Engineering Physics-II",
    subjectCode: "BAS-08",
    totalMarks: 100,
    credits: 5,
    type: "Theory",
  },
  {
    subjectName: "Graph Theory",
    subjectCode: "BMS-03/BAS-14",
    totalMarks: 100,
    credits: 5,
    type: "Theory",
  },
  {
    subjectName: "Object Oriented Modeling & C++",
    subjectCode: "BCS-04",
    totalMarks: 100,
    credits: 5,
    type: "Theory",
  },
  {
    subjectName: "Humanities & Social Science Electives",
    subjectCode: "BMS-**/BAS-**",
    totalMarks: 100,
    credits: 3,
    type: "Theory",
  },
  {
    subjectName: "Software Lab-II",
    subjectCode: "BCS-05",
    totalMarks: 100,
    credits: 2,
    type: "Practical",
  },
  {
    subjectName: "Applied Computational Methods",
    subjectCode: "BMS-06/BAS-24",
    totalMarks: 100,
    credits: 5,
    type: "Theory",
  },
  {
    subjectName: "Discrete Mathematics",
    subjectCode: "BMS-05/BAS-27",
    totalMarks: 100,
    credits: 5,
    type: "Theory",
  },
  {
    subjectName: "Introduction to C & Functional Programming",
    subjectCode: "BCS-11",
    totalMarks: 100,
    credits: 5,
    type: "Theory",
  },
  {
    subjectName: "Principles of Data Structures",
    subjectCode: "BEE-01",
    totalMarks: 100,
    credits: 5,
    type: "Theory",
  },
  {
    subjectName: "Professional Communication",
    subjectCode: "BHM-01/BAS-03",
    totalMarks: 100,
    credits: 4,
    type: "Theory",
  },
  {
    subjectName: "Software Lab-III",
    subjectCode: "BCS-14",
    totalMarks: 100,
    credits: 2,
    type: "Practical",
  },
  {
    subjectName: "Optimization Techniques",
    subjectCode: "BMS-09/BAS-26",
    totalMarks: 100,
    credits: 4,
    type: "Theory",
  },
  {
    subjectName: "Management Information System",
    subjectCode: "MBA-113",
    totalMarks: 100,
    credits: 5,
    type: "Theory",
  },
  {
    subjectName: "Theory of Computation",
    subjectCode: "BCS-16",
    totalMarks: 100,
    credits: 4,
    type: "Theory",
  },
  {
    subjectName: "Computer Organization of design",
    subjectCode: "BEE-01",
    totalMarks: 100,
    credits: 5,
    type: "Theory",
  },
  {
    subjectName: "Professional Communication",
    subjectCode: "BHM-01/BAS-03",
    totalMarks: 100,
    credits: 4,
    type: "Theory",
  },
];
